name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.1

    - name: Setup .NET
      uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: '7.x'
    
    - name: Restore dependencies
      run: dotnet restore
      working-directory: 'src/Web'
    
    - name: Build
      run: dotnet build --no-restore
      working-directory: 'src/Web'
    
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: 'tests/UnitTests'

    - run: ls -la
    
    # - name: Publish Unit Test Results
    #   uses: EnricoMi/publish-unit-test-result-action@v2.11.0
    #   if: always()
    #   with:
    #     files: ./TestResults/*.trx
    
    - name: Step Summary for Test Cases
      uses: actions/github-script@v5
      with:
        script: |
          const fs = require('fs');
          let summary = '';
          const testResults = fs.readdirSync('./TestResults').filter(fn => fn.endsWith('.trx'));
          for (const fn of testResults) {
            const content = fs.readFileSync(`./TestResults/${fn}`, 'utf8');
            // parse content and create summary
          }
          console.log(summary);
    
    - name: Publish
      run: dotnet publish -c Release -o ${{ github.workspace }}/publish
    
    - name: Upload the artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: artifact-${{ github.run_number }}
        path: ${{ github.workspace }}/publish/*
